# Generated by Django 3.0.7 on 2022-03-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='level',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
