# Generated by Django 3.0.7 on 2022-03-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20220320_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_basic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_standard',
            field=models.BooleanField(default=False),
        ),
    ]
