# Generated by Django 3.0.7 on 2022-03-10 21:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=100)),
                ('has_payed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('address', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=100)),
                ('rent', models.IntegerField()),
                ('gender_required', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Both', 'Both')], max_length=30)),
                ('distance_from_campus', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('capacity', models.IntegerField()),
                ('front_image', models.ImageField(upload_to=core.models.directory_path_house)),
                ('room1', models.ImageField(upload_to=core.models.directory_path_house)),
                ('room2', models.ImageField(upload_to=core.models.directory_path_house)),
                ('room3', models.ImageField(upload_to=core.models.directory_path_house)),
                ('slug', models.SlugField()),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
