# Generated by Django 3.0.7 on 2022-03-10 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('landlords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landlords.LandlordProfile'),
        ),
        migrations.AddField(
            model_name='booking',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.House'),
        ),
    ]
