# Generated by Django 3.0.7 on 2022-03-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_booking_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='distance_from_campus',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
