# Generated by Django 3.0.7 on 2022-03-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220310_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='area',
        ),
        migrations.AddField(
            model_name='house',
            name='location',
            field=models.CharField(choices=[('Selborne Park 1', 'Selborne Park 1'), ('Selborne Park 2', 'Selborne Park 2'), ('Parklands', 'Parklands'), ('Khumalo', 'Khumalo'), ('Riverside', 'Riverside'), ('Sunminghill', 'Sunminghill'), ('Woodlands', 'Woodlands'), ('Matsheomuhlope', 'Matsheomuhlope')], default=4, max_length=100),
            preserve_default=False,
        ),
    ]
