# Generated by Django 3.0.7 on 2022-03-21 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20220321_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.House'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
