# Generated by Django 3.0.7 on 2022-03-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220325_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='landlord',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
