# Generated by Django 3.0.7 on 2022-03-25 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0002_landlordprofile_user'),
        ('core', '0013_auto_20220325_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landlords.LandlordProfile'),
        ),
    ]
